version: '3.8'

services:
  web:
    build: ./newproject-django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./newproject-django/:/usr/src/newproject-django/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev